# Generated by Django 5.0.6 on 2024-06-21 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, upload_to='perfis')),
                ('nome_usuario', models.CharField(blank=True, max_length=255)),
                ('imagem', models.ImageField(blank=True, upload_to='postagens')),
                ('legenda', models.TextField()),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True)),
                ('curtidas', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
