# Generated by Django 5.0.6 on 2024-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_post_delete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacidade',
            field=models.BooleanField(default=False),
        ),
    ]
