# Generated by Django 5.0.6 on 2024-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_post_privacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='./static/assets/perfis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='./static/assets/postagens'),
        ),
    ]
