# Generated by Django 5.0.6 on 2024-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacidade',
            field=models.BooleanField(default=True),
        ),
    ]
