# Generated by Django 5.0.6 on 2024-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_post_privacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
